sudo: required

language: go

go:
  - 1.7.x

services:
  - docker

install: true

script:
  - go build -o bin/demo
  - docker build -t fest/demo .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push fest/demo;
    fi