kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: fest/demo
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: demo